# Generated by Django 4.2.4 on 2023-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Full name'),
        ),
    ]
