# Generated by Django 4.2.4 on 2023-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
